captureDirectory: captures # Where you want the captures to be saved to
completeDirectory: complete # Where you want the "finalized" captures to be moved to as soon as model stops streaming
modelScanInterval: 60 # In seconds, how often showuptv-node checks for newly-online models
debug: true
rtmpDebug: false
minFileSizeMb: 5
models:
  - AAA
  - BBB
  - CCC
